name: 'setup-lesson-deps'
description: 'Action to set up package dependencies for Carpentries Lessons'
author: 'Zhian N. Kamvar'
inputs:
  cache-version:
    description: 'The version of the cache, change this from the default (1) to start over with a fresh cache'
    required: true
    default: 1
runs:
  using: "composite"
  steps:
      - name: "Restore {renv} Cache"
        uses: actions/cache@v2
        with:
          path: ${{ env.RENV_PATHS_ROOT }}
          key: ${{ runner.os }}-${{ inputs.cache-version }}-renv-${{ hashFiles('**/renv.lock') }}
          restore-keys:
            ${{ runner.os }}-${{ inputs.cache-version }}-renv-

      # NOTE: Right here, I need to write a jq script that will extract the
      #       packages needed for the lesson and pass it to R so that I can 
      #       install the dependencies for these packages.
      - name: "Setup System Dependencies"
        shell: Rscript {0}
        run: |
          wd <- '${{ github.workspace }}'
          has_lock <- file.exists(file.path(wd, 'renv'))
          if (Sys.info()[["sysname"]] == "Linux" && has_lock) {
            if (!requireNamespace("renv")) {
              install.packages("renv", repos = "https://cran.rstudio.com")
            }
            if (!requireNamespace("pak")) {
              install.packages("pak", repos = "https://r-lib.github.io/p/pak/stable/")
            }
            Sys.setenv("RENV_PROFILE" = "lesson-requirements")
            lock <- renv:::lockfile(renv::paths$lockfile())$data()
            pkgs <- names(lock$Packages)
            db <- available.packages()
            compiled <- db[, "Package"] %in% pkgs & db[, "NeedsCompilation"] == "yes"
            pkgs <- db[compiled, "Package", drop = TRUE]
            ver <- tolower(system("lsb_release -irs", intern = TRUE))
            # pkgs <- pak::pkg_deps(pkgs, upgrade = FALSE, dependencies = FALSE)
            # to_compile <- pkgs$needscompilation & pkgs$type == "standard"
            seen <- character(0)
            for (dep in pkgs) {
              if (dep == "stringi") { # We have this one taken care of
                next
              }
              these <- pak::pkg_system_requirements(
                os = ver[1], os_release = ver[2], package = dep, execute = FALSE
              )
              these <- sub('apt-get install -y ', '', these)
              new <- setdiff(these, seen)
              if (length(new)) {
                seen <- c(seen, new)
                cmd <- paste(new, collapse = " ")
                cmd <- paste("sudo apt-get install -y", cmd)
                cat("Executing", cmd, "\n")
                processx::run("sh", c("-c", cmd), stdout_callback = NULL,
                  stderr_to_stdout = TRUE)
              }
            }
          }
      - name: "Fortify Local {renv} Packages"
        shell: Rscript {0}
        run: |
          wd <- '${{ github.workspace }}'
          if (file.exists(file.path(wd, 'renv'))) {
            if (!requireNamespace("renv")) {
              install.packages("renv", repos = "https://cran.rstudio.com")
            }
            if (!requireNamespace("pak")) {
              install.packages("pak", repos = "https://r-lib.github.io/p/pak/stable/")
            }
            Sys.setenv("RENV_PROFILE" = "lesson-requirements")
            lock <- renv:::lockfile(renv::paths$lockfile())$data()
            pkgs <- names(lock$Packages)
            options(repos = c(RSPM = Sys.getenv("RSPM"), getOption("repos")))
            pak::pkg_install(pkgs, upgrade = FALSE, dependencies = FALSE)
            sandpaper::manage_deps(path = wd, quiet = FALSE)
          } else {
            writeLines("Package cache not used")
          }

      - name: Don't use tar 1.30 from Rtools35 to store the cache
        shell: bash
        run: |
          if command -v /c/Rtools/bin/tar && /c/Rtools/bin/tar --version | grep -q 'tar (GNU tar) 1.30'
            then echo 'C:/Program Files/Git/usr/bin' >> $GITHUB_PATH
          fi
