name: "Update Workflows"
description: "Update GitHub Action Workflows for {sandpaper} repoisitories"
inputs:
  version:
    description: "Version of {sandpaper} to use"
    required: false
    default: 'current'
  repo:
    description: "CRAN-like repository to get the workflow files"
    required: false
    default: "https://caprentries.r-universe.dev/"
  clean:
    description: "Regex for workflow files to be cleaned before update. Defaults to all *.yaml files."
    required: false
    default: '*.yaml'
outputs:
  old: 
    description: "old version of {sandpaper}"
    value: "${{ steps.update.output.old }}"
  new:
    description: "new version of {sandpaper}"
    value: "${{ steps.update.output.new }}"
runs:
  using: "composite"
  steps: 
    - name: "Update Workflows"
      run: ${{ github.action_path }}/update-workflow.sh ${{ inputs.version }} ${{ inputs.repo }} ${{ inputs.clean }}
      shell: bash
