name: 'Add or Update a Comment on a Pull Request'
description: 'This action will take in a pull request number and comment body and add or update a comment on the pull request with information about staging'
inputs:
  pr:  # id of input
    description: 'pull request number'
    required: true
  repo:
    description: 'github repository'
    required: true
    default: ${{ github.repository }}
  token:
    description: 'github token'
    required: true
  body:
    description: 'body of the comment as a string'
    required: false
  path:
    description: 'path to a file to use for the body'
    required: false
runs:
  using: 'node12'
  main: 'index.js'
