name: 'Check Valid Pull Request'
description: 'Checks that a Pull request is open and that it does not contain any .github files'
inputs:
  pr:  # id of input
    description: 'pull request number'
    required: true
  repo:
    description: 'github repository (default: ${{ github.repository }})'
    required: false 
    default: ${{ github.repository }}
  sha:
    description: 'sha of the latest head'
    required: false
    default: null
  token:
    description: 'github token'
    required: true
outputs:
  VALID: 
    description: "flag indicating if the PR is valid. 'true' if valid, 'false' otherwise"
  payload:
    description: "the JSON from the pull request call"
runs:
  using: 'node12'
  main: 'index.js'
