name: "Update Styles"
description: "Update Repository to use the latest version of the Carpentries Styles"
inputs:
  commit:
    description: "Should changes be committed?"
    required: false
    default: true
outputs:
  update:
    description: "true if a pull request needs to be created"
    value: ${{ steps.update.outputs.update }}

runs:
  using: "composite"
  steps:
    - name: "Update Styles"
      id: update
      run: ${{ github.action_path }}/update-styles.sh 
      shell: bash
    - name: "Commit Changes"
      id: commit
      run: |
        if [[ ${{ inputs.commit }} == 'true' ]]; then
          echo "Adding merge commit"
          git config --local user.email "team@carpentries.org"
          git config --local user.name "The Carpentries Bot"
          git commit -m "Sync lesson with carpentries/styles"
        else
          echo "Creating squash commit later"
        fi
      shell: bash
