name: "Update Styles"
description: "Update Repository to use the latest version of the Carpentries Styles"
inputs:
  commit:
    description: "Should changes be committed?"
    required: false
    default: true

runs:
  using: "composite"
  steps:
    - name: "Update Styles"
      id: update
      run: ${{ github.action_path }}/update-styles.sh 
      shell: bash
    - name: "Commit Changes"
      run: |
        if [[ ${{ inputs.commit == 'true' }} ]]; then
          git config --local user.email "team@carpentries.org"
          git config --local user.name "The Carpentries Bot"
          git commit -m "Sync lesson with carpentries/styles"
        fi
      shell: bash
