name: 'setup-deps'
description: 'Action to set up package dependencies for Carpentries Lessons'
author: 'Jim Hester'
inputs:
  cache-version:
    description: 'The version of the cache, change this from the default (1) to start over with a fresh cache'
    required: true
    default: 1
  extra-packages:
    description: 'Any extra packages to install outside of sandpaper and its dependencies'
runs:
  using: "composite"
  steps:
      - name: "Check if We Need {renv}"
        id: renv
        run: |
          if [[ -d renv ]]; then
            echo "::set-output name=exists::true"
          fi

      - name: "Restore {renv} Cache"
        if: ${{ steps.renv.outputs.exists }}
        uses: actions/cache@v2
        with:
          path: ${{ env.RENV_PATHS_ROOT }}
          key: ${{ runner.os }}-renv-${{ hashFiles('**/renv.lock') }}
          restore-keys:
            ${{ runner.os }}-renv-

      - name: "Fortify Local {renv} Packages"
        if: ${{ steps.renv.outputs.exists }}
        run: sandpaper::manage_deps(path = '${{ github.workspace }}', quiet = FALSE)
        shell: Rscript {0}

      - name: Don't use tar 1.30 from Rtools35 to store the cache
        shell: bash
        run: |
          if command -v /c/Rtools/bin/tar && /c/Rtools/bin/tar --version | grep -q 'tar (GNU tar) 1.30'
            then echo 'C:/Program Files/Git/usr/bin' >> $GITHUB_PATH
          fi
