on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Testing a PR that's closed
    steps:
    - uses: actions/checkout@v2
    - id: invalid-pr
      uses: zkamvar/check-valid-pr@use-js
      with:
        pr: 227
        repo: 'grunwaldlab/poppr'
        token: ${{ secrets.GITHUB_TOKEN }}
    - run: echo ${{ steps.invalid-pr.outputs.VALID }}
      shell: bash
    - id: valid-pr
      uses: zkamvar/check-valid-pr@use-js
      with:
        pr: 228
        repo: 'grunwaldlab/poppr'
        token: ${{ secrets.GITHUB_TOKEN }}
    - id: non-existant-pr
      uses: zkamvar/check-valid-pr@use-js
      with:
        pr: 20210104
        repo: 'grunwaldlab/poppr'
        token: ${{ secrets.GITHUB_TOKEN }}
    - run: echo ${{ steps.valid-pr.outputs.VALID }}
      shell: bash
