on: [push]

jobs:
  test:
    runs-on: ubuntu-20.04
    name: Testing PR states
    steps:
    - uses: actions/checkout@v2
    - id: valid-pr
      name: "Valid PR"
      uses: zkamvar/actions/check-valid-pr@main
      with:
        pr: 4
        repo: 'zkamvar/actions'
        token: ${{ secrets.GITHUB_TOKEN }}
        sha: '7237b06c519da8d35dd825df76785aacb1ae519e'
    - id: spoofed-pr
      name: "Spoofed PR"
      uses: zkamvar/actions/check-valid-pr@main
      with:
        pr: 3
        repo: 'zkamvar/actions'
        token: ${{ secrets.GITHUB_TOKEN }}
        sha: '7237b06c519da8d35dd825df76785aacb1ae519e'
    - id: invalid-pr-closed
      name: "Invalid PR (status)"
      uses: zkamvar/actions/check-valid-pr@main
      with:
        pr: 227
        repo: 'grunwaldlab/poppr'
        token: ${{ secrets.GITHUB_TOKEN }}
    - id: invalid-pr-files
      name: "Invalid PR (files)"
      uses: zkamvar/actions/check-valid-pr@main
      with:
        pr: 228
        repo: 'grunwaldlab/poppr'
        token: ${{ secrets.GITHUB_TOKEN }}
    - id: closed
      name: "Closed PR"
      uses: zkamvar/actions/check-valid-pr@main
      with:
        pr: 21
        repo: 'zkamvar/testme'
        token: ${{ secrets.GITHUB_TOKEN }}
    - id: echo-results
      name: "Echo Payloads"
      run: |
        echo ${{ steps.valid-pr.outputs.payload }}
        echo ${{ steps.spoofed-pr.outputs.payload }}
        echo ${{ steps.invalid-pr-closed.outputs.payload }}
        echo ${{ steps.invalid-pr-files.outputs.payload }}
        echo ${{ steps.closed.outputs.payload }}
