name: "Validate Pull Request"

on:
  workflow_run:
    workflows: ["Receive Pull Request"]
    types:
      - completed

jobs:
  upload:
    runs-on: ubuntu-latest
    if: >
      ${{ github.event.workflow_run.event == 'pull_request' &&
      github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: 'Download artifact'
        uses: zkamvar/actions/download-workflow-artifact@main
        with:
          run: ${{ github.events.workflow_run.id }}
          repo: ${{ github.repository }}
          name: 'pr'
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: "Get PR Number"
        id: get-pr
        run: |
          unzip pr.zip
          echo "::set-output name=NUM::$(cat ./NUM)"
      
      - name: "Check PR"
        id: check-pr
        uses: zkamvar/actions/check-valid-pr@main
        with:
          pr: ${{ steps.get-pr.outputs.NUM }}
          sha: ${{ github.events.workflow_run.head_commit.sha }}
          repo: ${{ github.repository }}
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: "Inspect Payload"
        run: |
          if [ ${{ steps.check-pr.outputs.VALID == 'true' ]; then
            echo "It's valid!"
          else
            echo "INVALID"
          fi
          echo ${{ steps.check-pr.outputs.payload }}
